version: "3.8"

services:
  sandbox:
    container_name: java-sandbox-service
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # link to host docker socket
      - submissions:/app/work

volumes:
  submissions:
    name: submissions
