name: Build Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t java-sandbox-service:latest .
    
    - name: Run container java-sandbox-service
      run: |
        docker run -d -p 3000:3000 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v submissions:/app/work \
        java-sandbox-service:latest

    - name: Wait container start finish
      run: |
        sleep 10

    - name: Test Call API
      run: |
        curl -X GET http://localhost:3000/java-sandbox-service/ || exit 1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag java-sandbox-service:latest ${{ secrets.DOCKER_USERNAME }}/java-sandbox-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/java-sandbox-service:latest

